### PR TITLE
Silence some new gcc warnings.

### PR DESCRIPTION
**Pull request by papadop**
With gcc-4.8.2 some new warnings are added to -Wall. Notably there is one that shows locally defined types that are not used. This patch set corrects those warnings.

### CODE REVIEW

**Comment by ocommowi** [comment]
Works for me. Can someone on windows try this quickly ?

**Comment by Hakim-F** [comment]
I have got one error on Windows, you need to add ITKIOMRC to the variable QTDCM_LIBRARIES in the CMakeLists.txt and it should be fine.

**Comment by ocommowi** [comment]
I've had it as well. Try to rebase and tell me if it works (this branch was created apparently before the move to ITK 4.5).

**Comment by Hakim-F** [comment]
ok good.

**Pull request merged**
